In [3]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

Different shapes of Tensors:

1D Array:
shape (4) : [1, 2, 3, 4]

2D Array:
shabe (2, 3): [1, 2, 3]
              [1, 2, 3]

|  /\ Axis 3 (depth)
|  /
| /
|/----------> Axis1
\/ 
Axis 0

Tensors can be used with:
nd-arrays
(GPU supports)
Computational graphs

Tensors are immutable (you can NEVER update a certain Tensor)
...unless its a tf.Variable()

In [4]:
#Scalar tensor
x = tf.constant(4, shape=(1))
print(x)

tf.Tensor([4], shape=(1,), dtype=int32)


2023-03-09 16:23:17.418273: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [5]:
#Higher dimensional tensor
#Rank 1 tensor: 
x = tf.constant([1,2,3])

#Rank 2 tensor:
y = tf.constant([x.numpy(),x.numpy()])

print(x)
print(y)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [1 2 3]], shape=(2, 3), dtype=int32)


In [6]:
#Fill tensors with values
x = tf.zeros((2,3))

y = tf.eye(3)

z = tf.random.normal((3,3), mean = 0, stddev=1)

print(x)
print(y)
print(z)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-1.3524272   2.6253724  -0.8653361 ]
 [ 0.7784974  -1.1032395  -0.30458698]
 [-1.1548123  -1.0111063  -1.4635035 ]], shape=(3, 3), dtype=float32)


In [7]:
#Cast tensors to other types
z = tf.cast(z, dtype='int32')

print(z)

tf.Tensor(
[[-1  2  0]
 [ 0 -1  0]
 [-1 -1 -1]], shape=(3, 3), dtype=int32)


Operations

All operations are element wise
possible are:
+ (or .add)
- (or .substract)
* (or .multiply)
/ (or .divide)

Also possible:
exponential: x ** 2
matrixmultiplikation: @ ( or .matpul(x,y))



In [8]:
x = tf.constant([1,2,3])
y = tf.constant([3,2,1])

In [9]:
z = tf.add(x,y)
print(z)

tf.Tensor([4 4 4], shape=(3,), dtype=int32)


Indexing and slicing

In [10]:
#Indexing
print(x[0])

z = tf.constant([[1,2],[3,4]])
print(z[0,:])

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)


In [11]:
#Reshaping

z = tf.reshape(z, (4))
print(z)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [12]:
#converting

z = tf.convert_to_tensor(z.numpy())
print(z)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


*Magic*

Creating a Model with the keras method

there are two methods, a class based and keras, keras is more beginner friendly :D

it is good practice to normalize data first

x_data = x_data / maxVal

the naming should be like this:
x_train: All the training inputdata, stored as a tensor
y_train: All the goal outputdata, " "
x/y_test: The Testdata, mabe with the outputvalues y


In [13]:
#Create the basic model blueprint
model = keras.models.Sequential([
    #Input layer
    keras.layers.Flatten(input_shape=(28,28)),
    
    #Hidden layer(s) 
    keras.layers.Dense(128, activation = 'relu'),
    
    #output layer
    keras.layers.Dense(10, activation = 'softmax'),
])

print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 128)               100480    
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________
None


In [14]:
#finish the model blueprint with loss and optimisation function
loss = keras.losses.SparseCategoricalCrossentropy()
optimizer = keras.optimizers.Adam(learning_rate=0.001)
metrics = ["accuracy"] #what do we wanna keep track of?
                      #The string version of this command could cause a bug!!!
#Note: the learning rate is a good hyperparameter to tweak
#      to make the NN learn at the best / optimal rate not too fast / slow

model.compile(loss=loss, optimizer=optimizer, metrics=metrics)

In [16]:
#Now, if we would have data, we could train the NN
#just like this:
batch_size = 64 #how many things should be loaded to the RAM in one epochcycle
epochs = 5      #how many times does a batch repeat
verbose = 0     #how much output should be displayed

model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, shuffle=True
          , verbose=verbose)

NameError: name 'x_train' is not defined

In [17]:
#Next we wanna see how good our model is doing on some test data

model.evaluate(x_test, y_test, batch_size=batch_size, verbose=2)

NameError: name 'x_test' is not defined

In [18]:
#At (almost) last we wanna make some real world predictions

predictions = model(x_test) # for all the test data
predictions = model(x_test[0]) # for just one data

pred0 = predictions([0]) # get the (first) prediction
label0 = np.argmax(pred0) # get the most likely label
print(label0)

NameError: name 'x_test' is not defined

In [19]:
#Finally we wanna save our beautiful NN
#There are three options for that:

#1. safe whole model
model.save(r"nice\path\myModel")
#if you add ".h5" it will be stored too, but differently 
#otherwise it creates a whole folter lol

#2. save only weights
model.save_weights(r"nice\path\myModelWeights")

#3. safe only architecture
json_string = model.to_json()
with open(r"nice\path\myModelWeights", "w") as f:
    f.write(json_string)    

INFO:tensorflow:Assets written to: nice\path\myModel/assets


In [20]:
#Next day we wanna load a model, we do it like this:

#1.
model = keras.models.load_moddel(r"nice\path\myModel")

#2.
model.load_weights(r"nice\path\myModelWeights")

#3.
with open(r"nice\path\myModelWeights", "r") as f:
    loaded_json_string = f.read()

model = keras.models.model_from_json(loaded_json_string)

AttributeError: module 'keras.api._v2.keras.models' has no attribute 'load_moddel'

Special networks:

- Convolutional networks CNNs
Use 2-XD convolution on images for example
the convolution matrix is learned

- Recurrent neural nets RNNs
Remember some past things to feed as input for the current state, different types, for our case we need the "many to many" OR the "many to one" approach
Important: the number of sequences should be known!

In [21]:
#Convolutional network
#...is build like this:
model = keras.models.Sequential([
    #Input layer
    keras.layers.Conv2D(32, (3,3), strides=(1,1), padding="valid", activation="relu", input_shape="32,32,3"),
    keras.layers.MaxPool2D((2,2)),
    keras.layers.Conv2D(32, 3, strides=(1,1), activation="relu"),
    keras.layers.MaxPool2D((2,2)),
    #...repeat until happy...
    
    #Flatten layer: make 1D out of 2D
    keras.layers.Flatten(input_shape=(28,28)),
    
    #Hidden layer(s) 
    keras.layers.Dense(128, activation = 'relu'),
    
    #output layer
    keras.layers.Dense(10, activation = 'softmax'),
])

print(model.summary())

TypeError: Dimension value must be integer or None or have an __index__ method, got value ''3'' with type '<class 'str'>'

In [22]:
#Recurrent network
#...is build like this:
model = keras.models.Sequential()

